image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test

build:
    stage: build
    script:
        - dotnet build src/Inflop.Shared.Extensions/Inflop.Shared.Extensions.csproj /p:Version=1.0.$CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA
    artifacts:
        name: "inflop-shared-extensions-1.0.$CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA"
        paths:
            - src/Inflop.Shared.Extensions/bin/Release/net6.0/            
    only:
        refs:
            - master
        variables:
            - $CI_COMMIT_MESSAGE =~ /(^|)(#build|#deploy|#publish)(|$)/

test:
    stage: test
    script: 
        - dotnet test src/Inflop.Shared.Extensions.Tests/Inflop.Shared.Extensions.Tests.csproj
